### ISSUE TITLE
[mobile]  section one the image should be reduce regarding the screen resolution

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/lobo#44]
http://quirktools.com/screenfly/#u=http%3A//lordalexworks.github.io/lobo/&w=320&h=568&a=37

the logo is too big

**Comment by bolom** [comment]
http://quick.as/gvoyfrg33

**Comment by accetone** [comment]
@bolom i think this issue solved too

**Comment by bolom** [comment]
no the images are not reduced 

http://quirktools.com/screenfly/#u=http%3A//lobo.studio&w=176&h=220&a=31

![capture d ecran 3](https://cloud.githubusercontent.com/assets/72155/14247856/14d2cc26-fa3f-11e5-9b7c-335a28532e44.png)
![capture d ecran 4](https://cloud.githubusercontent.com/assets/72155/14247857/14e8a3b6-fa3f-11e5-9bea-d134db5b4dbb.png)

**Comment by accetone** [comment]
@bolom i reduced size of images. if in some resolution you find that logos too big or too small, let me know
