### ISSUE TITLE
section 2 - mobile

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/lobo#49]
![capture d ecran 6](https://cloud.githubusercontent.com/assets/72155/14251567/9b6e6a4e-fa51-11e5-944d-fd4038dba529.png)
http://quirktools.com/screenfly/#u=http%3A//lordalexworks.github.io/lobo/&w=176&h=220&a=31

**Comment by bolom** [comment]
BO and LO are really two big

**Comment by accetone** [comment]
@bolom not yet, i fixed only first section on this week

**Comment by bolom** [comment]
okidoki
Bolo
(438) 792-9121

**Comment by accetone** [comment]
@bolom done

**Comment by bolom** [comment]
@accetone https://lookback.io/watch/he4JHwL9x2gswWLdT

**Comment by accetone** [comment]
@bolom fixed, please, check
