### ISSUE TITLE
section  2 - table / mobile - portrait mode

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/lobo#50]
http://quirktools.com/screenfly/#u=http%3A//lordalexworks.github.io/lobo/&w=768&h=1024&a=22

we should not see the cats only the circle with the animation

**Comment by bolom** [comment]
@accetone it's fixed?

**Comment by accetone** [comment]
@bolom not yet, i fixed only first section on this week

**Comment by accetone** [comment]
@bolom done

**Comment by bolom** [comment]
@accetone https://lookback.io/watch/c89duGipGHz2TcF49

**Comment by accetone** [comment]
@bolom i don't have access to this recording

**Comment by bolom** [comment]
you should have access now

2016-04-19 7:15 GMT-04:00 Nikita Tsyhanenko <notifications@github.com>:

**Comment by accetone** [comment]
@bolom fixed, please, check
