### ISSUE TITLE
Add google analytics to lobo.studio

### ISSUE THREAD

**Issue by lordalex** [LordAlexWorks/lobo#52]
I'd like this added as soon as we possibly can to measure the coming to our new site.

Thanks

**Comment by accetone** [comment]
@lordalex @bolom i will need tracking code

**Comment by bolom** [comment]
i did it myself

**Comment by bolom** [comment]
@accetone i have added the code but i don't see nothing https://github.com/LordAlexWorks/lobo/commit/3023017c84343fe26071f8e641dc1b2473804627

i did something wrong?

**Comment by accetone** [comment]
@bolom and now?

**Comment by bolom** [comment]
nothing :(

**Comment by accetone** [comment]
@bolom maybe something in your settings, because i passed my tracking code into ga('create') and see visitor in GA dashboard

**Comment by bolom** [comment]
i have data now !
Bolo
(438) 792-9121
