### ISSUE TITLE
section 3 - show only the title

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/lobo#55]
http://quirktools.com/screenfly/#u=http%3A//lordalexworks.github.io/lobo/&w=176&h=220&a=31

not the content

**Comment by accetone** [comment]
@bolom done

**Comment by bolom** [comment]
the font is too big

**Comment by bolom** [comment]
i can't scroll the view

**Comment by accetone** [comment]
@bolom strange I have scrollbar

**Comment by accetone** [comment]
@bolom i changed font-sizes, look please
